$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$sourceRoot = Join-Path $root "src\KryptexUI"
$distRoot = Join-Path $root "dist"
$distFile = Join-Path $distRoot "KryptexUI.lua"

function Read-LuaFile($path) {
	$content = [System.IO.File]::ReadAllText($path)
	return $content -replace "`r`n", "`n"
}

function Wrap-Module($variableName, $relativePath) {
	$path = Join-Path $sourceRoot $relativePath
	$content = Read-LuaFile $path

	return @"
local $variableName = (function()
$content
end)()

"@
}

$main = Read-LuaFile (Join-Path $sourceRoot "init.lua")
$main = $main -replace "local Create = require\(script\.Utility\.Create\)\n", ""
$main = $main -replace "local Maid = require\(script\.Utility\.Maid\)\n", ""
$main = $main -replace "local Theme = require\(script\.Utility\.Theme\)\n", ""

$output = @"
-- Generated by scripts/build-dist.ps1.
-- Do not edit this file directly. Edit src/KryptexUI instead.

"@

$output += Wrap-Module "Create" "Utility\Create.lua"
$output += Wrap-Module "Maid" "Utility\Maid.lua"
$output += Wrap-Module "Theme" "Utility\Theme.lua"
$output += $main

New-Item -ItemType Directory -Force -Path $distRoot | Out-Null
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($distFile, ($output -replace "`r`n", "`n"), $utf8NoBom)

Write-Output "Built $distFile"

